server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/spring_practice
    username: root
    password: root
  flyway:
    url: jdbc:mysql://localhost:3306/spring_practice
    locations: classpath:db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
jwt:
  password:
    encoder:
     secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
     iterations: 64
     keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: geopokrovskiy
